"""
Critic Agent:
- Evaluates the draft answer for hallucinations, unsupported claims, and missing context.
- Assigns a confidence score (0.0 - 1.0).
- Lists specific issues that the Refinement Agent should address.
"""
import json
import logging
from backend.agents.base import BaseAgent, AgentState
from backend.utils.llm import llm_generate

logger = logging.getLogger("apks.agent.critic")

SYSTEM_PROMPT = """You are a rigorous fact-checker and quality evaluator for an AI knowledge system.

You will be given:
1. The original user query
2. The retrieved evidence chunks
3. A draft answer generated by a reasoning agent

Your job is to critically evaluate the draft answer and assign a confidence score.

Evaluate the answer on these criteria:
- Faithfulness: Is every claim in the answer supported by the evidence? (not hallucinated)
- Completeness: Does the answer fully address the query?
- Citation accuracy: Are citations correct and traceable to the evidence?
- Conflict handling: Are contradictions between sources acknowledged?

Return ONLY valid JSON in this exact format:
{
  "confidence": <float between 0.0 and 1.0>,
  "faithfulness_score": <float 0-1>,
  "completeness_score": <float 0-1>,
  "issues": ["<specific issue 1>", "<specific issue 2>"],
  "missing_context": ["<topic or info that is missing>"],
  "unsupported_claims": ["<claim that appears hallucinated>"],
  "critique_summary": "<1-2 sentence evaluation summary>"
}

Scoring guide:
- 0.9-1.0: Excellent. All claims supported, comprehensive, well-cited.
- 0.7-0.9: Good. Minor gaps but fundamentally sound.
- 0.5-0.7: Adequate. Some unsupported claims or missing context.
- Below 0.5: Poor. Significant hallucinations or incomplete answer.
"""


class CriticAgent(BaseAgent):
    name = "CriticAgent"

    def execute(self, state: AgentState) -> AgentState:
        query = state.get("query", "")
        retrieved_chunks = state.get("retrieved_chunks", [])
        reasoning = state.get("reasoning", {})
        draft_answer = reasoning.get("draft_answer", "")

        if not draft_answer:
            state["critique"] = {
                "confidence": 0.0,
                "faithfulness_score": 0.0,
                "completeness_score": 0.0,
                "issues": ["No draft answer was generated."],
                "missing_context": ["Complete answer is missing."],
                "unsupported_claims": [],
                "critique_summary": "No answer to evaluate.",
            }
            return state

        # Format evidence summary
        evidence_summary = ""
        for i, chunk in enumerate(retrieved_chunks[:10]):  # limit to top 10
            source = chunk.get("metadata", {}).get("source", "Unknown")
            evidence_summary += f"[{i+1}] {source}: {chunk['content'][:200]}...\n"

        prompt = f"""User Query: "{query}"

Retrieved Evidence (summary):
{evidence_summary}

Draft Answer to Evaluate:
{draft_answer}

Reasoning Steps Used:
{reasoning.get('reasoning_steps', 'Not provided')}

Critically evaluate the draft answer and return your critique."""

        try:
            raw = llm_generate(
                prompt=prompt,
                system_instruction=SYSTEM_PROMPT,
                json_mode=True,
                provider=state.get("model_provider"),
                model_name=state.get("model_name"),
            )
            critique = json.loads(raw)
        except Exception as e:
            logger.error(f"CriticAgent failed: {e}")
            # Default to medium confidence to avoid infinite loops
            critique = {
                "confidence": 0.72,
                "faithfulness_score": 0.7,
                "completeness_score": 0.7,
                "issues": ["Critique agent encountered an error during evaluation."],
                "missing_context": [],
                "unsupported_claims": [],
                "critique_summary": "Evaluation failed; defaulting to medium confidence.",
            }

        state["critique"] = critique
        logger.info(f"CriticAgent complete. Confidence: {critique.get('confidence', 0):.2f}, Issues: {len(critique.get('issues', []))}")
        return state
